{{- $repoName := include "tenant.repoName" .Values.tenant.name }}
{{- $githubOrg := include "deploy.githubOrg" $ }}

apiVersion: repo.github.m.upbound.io/v1alpha1
kind: RepositoryFile
metadata:
  name: "{{ .Values.tenant.name }}-readme"
  namespace: "gitops-{{ .Values.tenant.name }}"
  labels:
{{ include "common.labels" . | nindent 4 }}
    platform.rezakara.demo/tenant: "{{ .Values.tenant.name | lower }}"
    platform.rezakara.demo/github-org: "{{ $githubOrg }}"

spec:
  providerConfigRef:
    kind: ClusterProviderConfig
    name: {{ printf "github-%s" $githubOrg | quote }}

  forProvider:
    repository: {{ $repoName | quote }}
    file: README.md
    branch: main
    commitMessage: "chore: post tenant details in README.md via Crossplane"
    content: |
    {{ tpl (.Files.Get "files/README.md") . | nindent 6 }}

---
