apiVersion: idp.fluxdojo.local/v1alpha1
kind: TenantRequest
metadata:
  name: payment
spec:
  name: payment
  dnsName: pay
  owner:
    team: payment
  environmentPrefix: wl
  gitops:
    syncRepos:
      - https://github.com/rezakaramad/kubepave.git
