apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-tsig
  namespace: platform-system
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: vault-local
    kind: SecretStore
  target:
    name: external-dns-tsig
    creationPolicy: Owner
  data:
    - secretKey: algorithm
      remoteRef:
        key: local/management/external-dns/rfc2136
        property: algorithm
    - secretKey: tsig_key_name
      remoteRef:
        key: local/management/external-dns/rfc2136
        property: tsig_key_name
    - secretKey: tsig_secret
      remoteRef:
        key: local/management/external-dns/rfc2136
        property: tsig_secret
