{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1" }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: root-ca
  namespace: platform-system
spec:
  refreshInterval: 20m
  secretStoreRef:
    name: vault-local
    kind: SecretStore
  target:
    name: root-ca
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: management/pki
        property: ca.crt
    - secretKey: tls.crt
      remoteRef:
        key: management/pki
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: management/pki
        property: tls.key

---
{{- end }}
