{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1" }}

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-local
  namespace: platform-system
spec:
  provider:
    vault:
      server: "https://vault.mgmt.rezakara.demo"
      path: "local"
      version: "v2"
      caProvider:
        type: Secret
        name: root-ca
        key: tls.crt
        namespace: platform-system
      auth:
        kubernetes:
          mountPath: "kubernetes-minikube-workload"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets

---
{{- end }}
