apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-management
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/micro-idp
    targetRevision: HEAD
    path: charts/crossplane
    helm:
      valueFiles:
        - values-management.yaml
  destination:
    name: in-cluster
    namespace: crossplane
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
