apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-mgmt
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/kubepave
    targetRevision: HEAD
    path: charts/external-dns
    helm:
      valueFiles:
        - values-mgmt.yaml
  destination:
    name: in-cluster
    namespace: platform-system
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
