apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-resources
  namespace: argocd
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/micro-idp
    targetRevision: HEAD
    path: charts/namespace-resources
    helm:
      valueFiles:
        - values-management.yaml
  destination:
    name: in-cluster
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
