apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: vault
spec:
  project: platform-system
  source:
    repoURL: https://github.com/rezakaramad/micro-idp
    targetRevision: dev
    path: charts/vault
  destination:
    name: in-cluster
    namespace: vault
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
