apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns-api-key
  namespace: platform-system
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: vault-local
    kind: ClusterSecretStore
  target:
    name: powerdns-api-key
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: local/powerdns/api
        property: key
