version: '3'
runner: bash

tasks:
  check:
    desc: "Verify required dependencies are installed"
    cmds:
      - ./bootstrap/check-dependencies.sh
  start:
    desc: "Start Minikube clusters"
    deps: [check]
    cmds:
      - ./bootstrap/start-minikube-clusters.sh
  up:
    desc: "Run Micro IDP"
    deps: [start]
    cmds:
      - ./bootstrap/install-platform-charts.sh
      - ./bootstrap/setup-environment.sh
  down:
    desc: "Tear down everything"
    cmds:
      - ./bootstrap/destroy.sh
